#!/usr/bin/env ruby
#^syntax detection

site 'http://community.opscode.com/api/v1'

cookbook 'nodejs', '1.3.0'
cookbook 'forever', :git => 'https://github.com/trabian/chef-forever'
cookbook 'git', :git => 'git@github.com:jssjr/git.git'

